### ISSUE TITLE
Content does not display all relationships

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#1]
When viewing content, relationships with other pieces of content are not always displayed. For instance, a project does not display all the content attached to it (eg, an attached dataset), and other pieces of content don't always show their parent projects or content attached to it (eg, a dataset not showing an attached codebook).

**Comment by bryjbrown** [comment]
The dev team is aware of this issue and will resolve after resolving webforms issues, as those may affect the way content relates to each other.

**Comment by WilhelminavanDijk** [comment]
This may part of the "visual representation" issue opened on May 15, but worded more technical? Maybe these two issues need to be merged?

**Comment by trreynolds** [comment]
This issue should include allowing people to see which codebooks are connected to which datasets. (For example, if a project has 10 codebooks and 10 datasets, you need to see which codebook belongs to which dataset. Currently it just lists them as existing for a project, but does not connect them.)

**Comment by bryjbrown** [comment]
9/3 audit notes: This is an old issue that is probably mostly resolved, but @Favenzio will do an audit of the current site displays to verify that all relationships are present, and implement any relationship displays that are missing at which point we'll set the status to "Needs Review" so they Psych team can give it a look.

**Comment by WilhelminavanDijk** [comment]
I think this has been solved.
