### ISSUE TITLE
Interface consistancy to-do list

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#100]
This is a container for some interface items that need addressing in order to present a cohesive "feel" to how the site looks and feels to use - add more as needed:

- Input fields should all be squared (project entry) or rounded (top search bar) but not a mix
- Buttons need standardization in size. Length can be different but height should at least remain the same (see Get Citation button)
- Download buttons for files should maintain same look and feel of other site buttons AND give the user a clue as to what they do "Download file xxxx" - currently they just show filename and a down arrow, which we also use for dropdowns
- Same rounded vs square decision needs to be made with the social media buttons. "Mixing rounded and square corners is usually considered poor design from an aesthetic point of view. " -The Internet

**Comment by barsenault-fsu** [comment]
- Input fields have been squared
- button height standardized and some buttons (like Get Citation) changed to links with images
- download buttons changed to links
- TODO: square social media buttons - need to override local-theme .resp-sharing-button

**Comment by barsenault-fsu** [comment]
Social media buttons now have square corners.  Pushed to produciton
