### ISSUE TITLE
Relational Database info

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#101]
On the dataset screen, if they select "Dataset will be uploaded", additional options appear. One of them is for "Dataset Version Upload." Please change the text below the upload box to this:
Upload your dataset here. We recommend storing your data in a non-proprietary format (e.g., .dat or .csv file). If you use relational databases, consider storing your data on LDbase as flat files or in a file format that is widely available (e.g., MS Access), as this makes it easier for others to reuse your data.
If you update your dataset in the future, remember you can change your file here on this screen through editing and versioning.
One file only.
0 bytes limit.
Examples of allowed types: dat, csv, xls, xlsx, xlsm, sav, sas7bdat, json, dta, jmp, rdata, rda, mtw, mtj, txt, pzf, pzfx, mat.

Brian - please change your 'behind the scenes' list of allowed file types to include: .fmp12, *.bak, and these access extensions (https://www.help4access.com/microsoft-access-file-extensions/).  You DON'T have to list all of these in the above text on the screen (too messy and we don't prefer them anyway!)
Also:  On the CODE screen (not dataset), you should be able to upload "*.sql" extension files. I tried and I couldn't, but maybe it was just me?

**Comment by barsenault-fsu** [comment]
I made these changes to the dataset and code forms and will update this with the Needs Review tag when it gets moved to Test.

@trreynolds FYI, you mention in the issue that I don't have to list all the Access options on the screen and that you don't prefer them, but the list of what's accepted and what's displayed come from the same place.  If the extension is accepted, then it's displayed as an allowable type.
