### ISSUE TITLE
CC by license - text change for Code, Codebook, Document screens

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#103]
Leave the DATASET screen as is!  But change the others to this:  (instead of material, it should say Code or Codebook or Document or whatever screen you are on, like it does now). 

Choose the license type for your material. There are many levels of Creative Commons (CC) licenses you can choose from. For full information about CC licenses, read about it in the Best Practices page (Brian, include a link there). If you opt to make your material public without a license, other users may use and reuse it without citing you and your team. If you have a license in mind that is not on the list, select the "Other" option and enter the type in the box.

**Comment by barsenault-fsu** [comment]
Updated the field description and added link to the License Types page that opens in a new window.  That should cover this issue and #104 .
Will update with Needs Review when it gets moved to Test
