### ISSUE TITLE
"Most recent" limits on Project page

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#105]
Add a "show more" link when limit is reached for recent items

**Comment by barsenault-fsu** [comment]
These displays were not displaying items that were nested in the project hierarchy.  I changed them to list all of each type of item as a list sorted by last update and a truncated description.  Now they are correctly displaying all items an don't need a "show more" link.

**Comment by barsenault-fsu** [comment]
This change is now on production.  There is no limit to the most recent item displays on the Project view
