### ISSUE TITLE
Update "Areas of expertise" help text in Profile

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#108]
Refer to the user in the second person

**Comment by trreynolds** [comment]
Areas of Expertise, please change the descriptive/help line to say, "Enter keywords related to your research interests. Examples: Decoding, Statistical Methods, Interventions, Genetics. Enter as many as you would like."  (Should the examples also/instead be pre-filled and gray like the other example text fields? I wasn't sure if it worked with a single box field like this.)
Other Profile text changes:
Delete "Preferred" from "Preferred Display Name" so it is just "Display Name"
Change "Thumbnail Image" to "Profile Picture"

**Comment by barsenault-fsu** [comment]
I updated the text. This is a taxonomy-driven field where users can add new terms, so it already has a link to view the taxonomy (see #112 ).  It is also a multiline field so I changed "Enter as many as you would like" to "Enter as many as you would like, each on its own line."

Will update to Needs Review when moved to Test

**Comment by barsenault-fsu** [comment]
Remove "Examples: ..." text from description.  Leave placeholder.
