### ISSUE TITLE
Limiters on search need help

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#109]
"Show all" is not intuitive to users - should say "remove limiter" or something similar
"Show more" needs to be bolded or more apparent
Selected limiters need to be moved to top of list and made to stand out

**Comment by barsenault-fsu** [comment]
Made some changes that are now on Test, but here is a screenshot from my local machine:
![image](https://user-images.githubusercontent.com/54671134/123862268-22a93100-d8f6-11eb-87ea-ff38a76c9894.png)

Changes:
1. "Show All" is now "Remove Limiters"
2. "Show More" (and "Show Less") are now bold
3. Selected limiters are moved to the top of the list and bolded.  (If there is more than one limiter they will all be at the top of the list and sorted by the count value in parentheses, descending)

**Comment by rkmase** [comment]
I think this is better, but a couple of suggestions: "Remove Limiter" still looks like its part of the list of limiters, it even has a bullet point - it needs to be separated somehow, since its not a limiter, its a higher function. Conversely, the "Show More" link is disjointed, and is too far disconnected from the options its showing more of. If you could just move it in-line with the rest of the options, closer to the options than the HR separator. I know this seems nit-picky but it helps the user by visually grouping/off-setting choices.

**Comment by barsenault-fsu** [comment]
Thanks, Mason.  I agree.  I've made some changes.  When they get pushed to Test and Production they will look like this

![image](https://user-images.githubusercontent.com/54671134/126006491-2c8961de-6e55-48ec-962d-4daaeef8d76a.png)

The idea being to move the "Remove Limiters" closer to the heading and left to appear "over" the bulleted list in the hierarchy.  The Show more link is in line with the list and closer.
