### ISSUE TITLE
Need a strategy for locking down editing of Person and Organization entities

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#11]
Currently anyone can edit any content in LDbase, though we are in the process of locking that down for Projects, Datasets, Code and Documents through the use of Project Groups. We need a similar solution for making sure that only the right people should be able to edit Person and Organization entities.

**Comment by barsenault-fsu** [comment]
Changed permissions and route access for Persons and Organizations.  Now only administrators can edit those nodes.  Other users can view them but cannot edit them.
Code: https://github.com/ldbase/ldbase_handlers/commit/cdcbfe47665468e57679b7d80a9ae258727b65b3
Config: https://github.com/ldbase/ldbase_config/commit/37c782aa72b57418fda93394ac84c8b6f914c4e2

**Comment by bryjbrown** [comment]
@barsenault-fsu I think we need additional functionality for allowing a user account for a person who is represented by an LDbase Person node to be able to edit that node as well. I think there's some sort of user account / LDbase person omniform that does both at once, is this correct?

**Comment by barsenault-fsu** [comment]
@bryjbrown When an LDbase user edits their profile (My Account > Edit your profile) they are editing the LDbase Person node associated with their account and may also change their password, which is part of their account.
