### ISSUE TITLE
Remove DOI creation form from edit workflow

### ISSUE THREAD

**Issue by barsenault-fsu** [ldbase/ldbase_issues#110]
"DOI screen annoying after first go" 

Only ask if user would like to mint a DOI when an item is created.  Do not ask when item is edited.

**Comment by barsenault-fsu** [comment]
Removed the question/form from the edit workflow.  Will update "needs review" label when it's moved to Test.

**Comment by trreynolds** [comment]
Sara said if you remove this screen (where it asks them if they'd like to create a DOI), then it needs to appear on the content's window "edit" screen. Because what if they need to come back and create a DOI? That is a feature of LDbase.
I'm thinking that could a problem though (because now we are asking for a field to appear ONLY if they're editing a content AND don't have a DOI, AND not creating the content for the first time)? Thoughts? or is this request ok?

**Comment by barsenault-fsu** [comment]
After 2/16 meeting where it was decided to only let users mint DOIs for Projects and Datasets, I 
1. Removed the DOI minting confirmation form Documents, Codebooks, and Code process
2. Added a checkbox to the Project and Dataset edit forms that appears if the user has not already saved a DOI to that object
3. The checkbox reads,  "Generate a DOI for this _____" and if checked takes the user to the DOI confirmation form upon submit
4. The description for DOI field changes based on the the conditions when the form is loaded:
     a. if it's the Add form, it reads, "If you already have a DOI for your dataset, enter it here. If you don't have a DOI yet, you will be provided the option to generate one when submitting this form."
     b. if it's the Edit form, and there is no DOI entered, it reads, "If you already have a DOI for your project, enter it here. If you don't have a DOI yet, you may check the option to generate one when submitting this form."
     c. if it's the edit form and there is already a DOI entered, then no checkbox appears to generate one, and the DOI description reads, "If you already have a DOI for your project, enter it here."  (DOI is a multiple text field, so they can enter more than one, but it seemed like we shouldn't be paying to mint DOIs for people that already have one.  Let me know if that should be changed.)

**Comment by barsenault-fsu** [comment]
These changes are on production.  Closing issue
