### ISSUE TITLE
Fix wording for all upload inputs, change position

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#111]
**Old**
"File" will be uploaded
"File" is an external resource 

**New**
I will Upload "File"
I have a URL for the "File"

Change this input to the last on each form

**Comment by Favenzio** [comment]
Let's change the input to first on all these forms. I think it makes more sense from the user's perspective.

**Comment by barsenault-fsu** [comment]
Changed working on the radio buttons (file upload/externally linked) for Code, Codebook, Dataset, Document forms.
Moved all the related fields up above name field (External URL, Publication Information, File Upload/Dataset version, Data User Agreement,, Restrict Public Access, Embargo Expiration, Embargo Exempt Users)

Will mark as Needs Review when moved to Test.

**Comment by trreynolds** [comment]
Just matching up the other words that surround this change. Can you do:
(Old header): Dataset uploaded or externally linked
(New header): Upload Dataset or Link to an external source
(Old): If your data are already stored online, select external resource and provide the online location information. If you are storing your data on LDbase select upload and follow the steps.
(New): If you are storing your data on LDbase, select upload and follow the steps. If your data are already stored online, select URL and provide the online location information. 
 I will upload the Dataset
 I have a URL that links to where my Dataset is already stored online elsewhere
