### ISSUE TITLE
Mason mentioned that testers said we need clarification and notices that the site is EU compliant for data storage

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#113]
We need to make sure we have the European Union equivalent security functions happening (GDPR) stuff added :) What 
Data security and transparency rights... and language on our website to let people know
I will try and look up some language on ICPSR and send it to you.

**Comment by trreynolds** [comment]
2/16/2021 meeting we decided Dev Team is researching this.

**Comment by rkmase** [comment]
This is my summary of what needs to be done if we want to be GDPR compliant, I'll be creating these issue in github and assigning as needed. : https://docs.google.com/spreadsheets/d/1DMnp0DbYqHkQdchIt8t2HvUolSSmndeYwiT6oH8UAnM/edit?usp=sharing
