### ISSUE TITLE
Contributions page

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#115]
On the "my dashboard" add a link to the a new page listing all LDbase "projects" this person has contributed to, but doesn't have editing privileges to

**Comment by barsenault-fsu** [comment]
I added a My Contributions button to the dashboard.  It links to the Person view which includes those items where a person is listed as a contributor.

Will update to Needs Review when the change is moved to Test.

**Comment by barsenault-fsu** [comment]
Button is on Dashboard.  Closing
