### ISSUE TITLE
GDPR Action Item - All data collected on users must be "opt-in"

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#116]
Any collected info on users must be opt-in, including cookies. Pop up on load to "agree to cookies" or "no cookies", forms should have an opt in for any data collected.

**Comment by barsenault-fsu** [comment]
In addition to the agreements that can be created/set in the GDPR module, there is an EU Cookie Compliance module for controlling cookies.  The documentation for that module is at https://www.drupal.org/docs/contributed-modules/eu-cookie-compliance/configuration

**Comment by Favenzio** [comment]
The EU Cookie compliance module has been installed and all information collection is now on an opt-in basis. Closing ticket.
