### ISSUE TITLE
GDPR Action Item - Clearly define data privacy policies (plain language) and make them easily accessible

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#118]
See article 13 and 14 : https://gdpr.eu/article-13-personal-data-collected/

**Comment by Favenzio** [comment]
Here is an example: https://gdpr.eu/wp-content/uploads/2019/01/Our-Company-Privacy-Policy.pdf

**Comment by barsenault-fsu** [comment]
Here is more information about writing the privacy policy  https://gdpr.eu/privacy-notice/
