### ISSUE TITLE
GDPR Action Item - Data control

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#119]
Mechanism to show a user, at their request, where their collected data is at all times, what information is being collected, how it's being used by whom, and when it's being accessed. Also ability to correct or delete this data when requested. This doesn't have to be on the user side, it just has to be available.

**Comment by barsenault-fsu** [comment]
The GDPR Module appears to have tools to help meet these requirements.  Documentation at https://freely-give.gitbook.io/gdpr/documentation especially sections Field List, Tasks, Viewing Stored Data, Subject Access Request, and Data Removal.
