### ISSUE TITLE
Visual representation of project structure

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#12]
Psych team would like the project home page to have a visual representation of the structure within the project. We think of this as a tree or a subway map or a TOC.

It would have the project, and it's affiliations at each level of affiliation. Ideally, you could click on each item and it would take you to that page. We think this same structure should be visible for other users when going to the project page to get a better sense of what's in it.

This would help project owners to know what they have uploaded and how it relates to each other (right know you cannot see where a code is, or which datasets have been uploaded), and it would help potential users to understand where a data set or code falls in the context of the larger project.

**Comment by bryjbrown** [comment]
First pass at such a feature: 
http://test.ldbase.org/projects/20536912-206c-4c09-866a-43a60726874b/tree

**Comment by WilhelminavanDijk** [comment]
Trees are so cool. The small tree on the left side is so helpful.
