### ISSUE TITLE
Text addition on "data set" form

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#122]
Hi,

We would like to add the following to the Participants descriptive text (can be after "view list of participant types") :
"School systems across the globe differ in grade designations. To ensure compatibility between data from different nations, we ask you to provide the age range of your participants instead of their grade."

**Comment by barsenault-fsu** [comment]
Change is done and on Test.

**Comment by barsenault-fsu** [comment]
Text is changed and on production.  Closing issue.
