### ISSUE TITLE
Odd behavior when using + - for address in Bio

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#124]
To reproduce: 
Go to bio, should see four lines for address "country, city, state, country(?)" Only city and county have + and -. Press + for city, form adds another country.

**Comment by barsenault-fsu** [comment]
Is this the Work Address Under the Bio field in the Profile edit form? I think you're describing the vertical alignment of the +/- buttons.

The Work Address field, with no data, has the Country field set to " -None- " and depending which country you select it may add city and state fields, or city and province fields, or City and Department fields, or just a city field.  Those fields appear in the left column of the row and the +/- is vertically aligned in the right column of the row.  Depending whether one or two fields gets added below country, it can look like the +/- is next to City or between Country and City, but it's the Add/Remove buttons for that row, not for the city.   If you add another row it's adding another Work Address starting with Country, not part of a Work Address.

Maybe style the table to show the alternating address rows more clearly?

**Comment by rkmase** [comment]
Ahh yes, now I see. I think this ended up confusing myself and the user. Sure, alternating rows may help? I'm honestly not sure the + - has ever been necessary given the duplication of a more clear "Add another" button we use.

**Comment by barsenault-fsu** [comment]
@Favenzio do you think the site needs some kind of tr:nth-child(even) style to shade the multiple Work Address rows on the Person profile form?

**Comment by Favenzio** [comment]
@barsenault-fsu I will add something to that effect today and see if it helps.

**Comment by Favenzio** [comment]
I added a gray background for even rows. @rkmase and @barsenault-fsu the update is in production. if you could check if it fixes the problem and comment on this issue, I would appreciate it.

**Comment by barsenault-fsu** [comment]
I like the alternating row color change.  I think it groups the changing fields of the work address.  I see it's also on all the multi row fields.  Looks good to me.

**Comment by Favenzio** [comment]
Solution accepted. Closing ticket.
