### ISSUE TITLE
Text for Data Upload User Agreement

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#127]
To be uploaded on the appropriate pages :)

**Comment by WilhelminavanDijk** [comment]
Oops. That was the wrong file.

Attached here the correct LD base upload user agreement
[LDbase Data Upload User Agreement_3.15.21.docx](https://github.com/ldbase/ldbase_issues/files/6393676/LDbase.Data.Upload.User.Agreement_3.15.21.docx)

**Comment by barsenault-fsu** [comment]
I entered the text on Production https://ldbase.org/data-upload-user-agreement

**Comment by barsenault-fsu** [comment]
Text is on Production.
