### ISSUE TITLE
Improve Home Page 'logged in' block

### ISSUE THREAD

**Issue by Favenzio** [ldbase/ldbase_issues#128]
Right now when you are logged in and you go home you get this tiny block on the right hand side that leads you back to the dashboard. I think it would be a good idea to turn this into a 'mini dashboard' of sorts that can take up the entire content region so that we don't have that white space on the left. Making this issue so we don't forget about this improvement.

**Comment by barsenault-fsu** [comment]
Links added to logged in block to more dashboard functionality

**Comment by barsenault-fsu** [comment]
Changes are on production.  Closing issue.
