### ISSUE TITLE
New submenu for resources

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#131]
Hi,

Can you make a new resources menu item called "data use versus data sharing agreements"?

It should follow the path Resources -> Best Practices -> Data use vs Data Sharing

I'm attaching the text!
[Data use agreements and Data sharing agreements.docx](https://github.com/ldbase/ldbase_issues/files/6461504/Data.use.agreements.and.Data.sharing.agreements.docx)

**Comment by barsenault-fsu** [comment]
The page is on production at https://ldbase.org/resources/best-practices/data-use-vs-data-sharing and ready for review
