### ISSUE TITLE
Data sharing template to upload

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#132]
Hi!

here is a link to the figshare, and the original text, of the data sharing agreement. To be put in Resources -> templates -> data use agreements

https://figshare.com/articles/preprint/Example_Data_Sharing_Agreement/14576049
[DataSharing_LDbase.docx](https://github.com/ldbase/ldbase_issues/files/6479060/DataSharing_LDbase.docx)

**Comment by barsenault-fsu** [comment]
The content is up at https://ldbase.org/resources/templates/example-data-sharing-agreement
