### ISSUE TITLE
Is it possible to log the person out of LDbase if they close the browser (and give them a message first if they have unsaved data or metadata)

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#133]
This was a Schotz request. Thoughts: worried about people logged in at a common lab computer; maybe accidentally editing someone else's data or adding a project under the wrong account.
Team zoom discussion: we also don't want to be annoying and log people out (timer wise) before they were ready.

**Comment by barsenault-fsu** [comment]
I figured out how to log a user out of LDbase when they close the browser, and it doesn't depend on the length of the session.  In other words, it will log you out only when you close the browser and not log you out in the background if you've been working a long time.  

It appears you get the same JavaScript alert if you try to close the browser and are on a form with unsaved changes as you have been getting when you try to navigate away from a form with unsaved changes.

This is on Test and ready for review.

**Comment by trreynolds** [comment]
I tested this on test, and it looks good! It logged me out automatically.

**Comment by barsenault-fsu** [comment]
Change has been moved to production.  Closing Issue
