### ISSUE TITLE
Tagline

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#136]
Can we add a slogan/tagline to our front page that says "A Project-Based Data Repository" right under the LDbase logo?
note to self: psy team will then tweak in other spots we see fit, like maybe the footer, etc.

**Comment by trreynolds** [comment]
6/8/21 meeting: Favenzio asked if our graphic artist could add the tagline as a part of the logo image rather than it being a text field. Schots said yes and asked me to ask Nathan. I sent a request to Nathan.

**Comment by barsenault-fsu** [comment]
Tagline image in different formats.

PNG
![ldbase_logo_tagline_horizontal_color](https://user-images.githubusercontent.com/54671134/125850681-d379cc93-d029-474d-84dc-c922149554d9.png)

PDF
[ldbase_logo_tagline_horizontal_color.pdf](https://github.com/ldbase/ldbase_issues/files/6825964/ldbase_logo_tagline_horizontal_color.pdf)

JPG
![ldbase_logo_tagline_horizontal_color](https://user-images.githubusercontent.com/54671134/125850686-32333510-75e7-4cce-a27e-40a4450ae4ce.jpg)

**Comment by barsenault-fsu** [comment]
This is on both Test and Production.  I removed some of the white space between the two lines so the row with the navigation wouldn't get too tall.  Even with that change I had to add some padding to the top of the main navigation menu to keep it centered in the row.
