### ISSUE TITLE
Homepage image

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#137]
I'm not sure if you have plans/designs in the works for the homepage other than what we are currently seeing, but until then, can we switch the main image from that FSU picture to this one?  Thanks!  I'll include the true image (should be around 2MB) and also the mockup image our graphic designer sent, just in case it helps to see both.
![ldbase_homepage_mockup](https://user-images.githubusercontent.com/64669172/123475468-6d127100-d5c9-11eb-852a-44849606eb78.jpg)
![ldbase_homepage_image_062521](https://user-images.githubusercontent.com/64669172/123475496-769bd900-d5c9-11eb-9c91-1a305877580a.jpg)

**Comment by barsenault-fsu** [comment]
This new image is ready for review on Test.

**Comment by trreynolds** [comment]
@barsenault-fsu  Looks good! After you put it on production, you can close this. We all reviewed it in our meeting today and gave it the thumbs up. Thanks!

**Comment by barsenault-fsu** [comment]
Now on production
