### ISSUE TITLE
Delete template page

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#138]
Please delete the 
resources: templates: data use agreement
page. We moved it to best practices and won't have a template for it, and it is obsolete.

**Comment by barsenault-fsu** [comment]
I deleted the page and I deleted the link to it from the Templates landing page.  

I'm just going to leave this open still while I explore a way to have those landing pages automatically reflect the content rather than have to manually update the list.

**Comment by barsenault-fsu** [comment]
I'm going to leave this issue open for now, because while deleting this page I had an idea to make the lists of links on the landing pages (for example https://ldbase.org/resources or https://ldbase.org/resources/templates) to be dynamic.  Not yet on production.

**Comment by barsenault-fsu** [comment]
This is now on Production.  Closing
