### ISSUE TITLE
Update text DOI

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#139]
Can you substitute the following to the DOI fields' subtexts? 

**Codebook:**
A digital object identifier provides a persistent link to a specific research output and makes it a citable product. A different DOI can be assigned to each of your research outputs, such as a project, dataset, published manuscript, survey, or conference presentation. Other researchers will be able to easily find your specific output through its DOI. If you already have a DOI for your codebook,
<img width="1141" alt="Screen Shot 2021-06-28 at 3 45 24 PM" src="https://user-images.githubusercontent.com/64925394/123695150-34bc9e00-d828-11eb-82e2-9022153e63cb.png">
 enter it here.

**Dataset:**
A digital object identifier provides a persistent link to a specific research output and makes it a citable product. A different DOI can be assigned to each of your research outputs, such as a project, dataset, published manuscript, survey, or conference presentation. Other researchers will be able to easily find your specific output through its DOI. If you already have a DOI for your dataset, enter it here.

**Project:**
A digital object identifier provides a persistent link to a specific research output and makes it a citable product. A different DOI can be assigned to each of your research outputs, such as a project, dataset, published manuscript, survey, or conference presentation. Other researchers will be able to easily find your specific output through its DOI. If you already have a DOI for your project, enter it here.

**Document:**
A digital object identifier provides a persistent link to a specific research output and makes it a citable product. A different DOI can be assigned to each of your research outputs, such as a project, dataset, published manuscript, survey, or conference presentation. Other researchers will be able to easily find your specific output through its DOI. If you already have a DOI for your material, enter it here.
material

**Comment by barsenault-fsu** [comment]
Changes are on Test and ready for review.

**Comment by WilhelminavanDijk** [comment]
oh shoot, I forgot the "code" one...
Document:
A digital object identifier provides a persistent link to a specific research output and makes it a citable product. A different DOI can be assigned to each of your research outputs, such as a project, dataset, published manuscript, survey, or conference presentation. Other researchers will be able to easily find your specific output through its DOI. If you already have a DOI for your code, enter it here.
material

**Comment by barsenault-fsu** [comment]
I committed the change.  When test and production are updated, the change should appear.

**Comment by WilhelminavanDijk** [comment]
Perfect. Closing this issue

**Comment by trreynolds** [comment]
Reopening this since we noticed that this text is sometimes not displaying (sometimes is/sometimes isn't) on only certain nodes.

**Comment by barsenault-fsu** [comment]
Found that text was getting changed programmatically from default text when editing.  Removed the code so that the form will always display the text set in the webform interface
