### ISSUE TITLE
User Error

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#14]
If a user makes a mistake, there is no way for them to fix it.  (What if they add a dataset that they did not mean to upload to Ldbase? What if they add a dataset or a document to the wrong project?)

**Comment by barsenault-fsu** [comment]
Users with the Project Administrator role (the user that created the project in LDbase and any users that the project owner gives the Project Administrator role) will be able to delete LDbase content. 

This will be reviewed in the 8/12 update meeting.  It's not on test yet.

**Comment by bryjbrown** [comment]
9/3 audit note: @barsenault-fsu has added "Delete Content" tasks on all LDbase content. Between the ability to edit and the ability to delete content, that should take care of any user error.

**Comment by trreynolds** [comment]
In summary: Project Admins can delete content. Thank you! I'll close this.
