### ISSUE TITLE
Software bug - "(unpublished)"

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#141]
If you have an unpublished Project, then add items/nodes to it (and they are, by default, unpublished also), it does not say "(unpublished)" after them in treeview, and it should.  example: adding code, a document, a dataset.

**Comment by barsenault-fsu** [comment]
Good catch.  I have made the fix.  Once Test is updated I will mark this as Needs Revew.

**Comment by barsenault-fsu** [comment]
This fix has been pushed to test and production

**Comment by trreynolds** [comment]
It looks great, @barsenault-fsu! Thanks!

**Comment by barsenault-fsu** [comment]
Moved to Production
