### ISSUE TITLE
When there are multiple pages of information to view, what is the web standard for displaying that?

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#145]
At the bottom of our webpages, sometimes you provide an option to scroll through multiple pages. Usually, it says "First Previous 1 2 3 Next Last" with buttons on each of those words. But sometimes it just says "Page 1 Next" or "Page 1 >>"  Can you default the ones that only show Page1  to the other example you've used (above) or something like 'Page 1 of XX' so that users know there are many more pages to click to/through?

examples = My Dashboard (clicking to next page of unread messages), The Taxonomy lists ( example https://ldbase.org/taxonomy/schooling)

**Comment by barsenault-fsu** [comment]
Would this be acceptable? The full pager plus a footer that shows your place in the universe of pages:

![image](https://user-images.githubusercontent.com/54671134/125854097-a26f749e-6fc7-45dc-be33-8c9adf9d83b1.png)

**Comment by trreynolds** [comment]
Yes! This looks really good! We like that it says the total pages number on bottom too. Thanks.

**Comment by barsenault-fsu** [comment]
Changes moved to production.  If you find any pages that I missed, just let me know.
