### ISSUE TITLE
New homepage button - First Time Storing Data

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#147]
Need a new "button" on the home page. Will be 5th in the series after Browse, Resources, Search, Add Data.
Button's text (a suggestion, I realize this might look too long): "It's My First Time Storing Data On LDbase"  (too long? Maybe: First Time Storing Data) 
Text link should also be housed under Menu: About (that is what we said in our team meeting, but I'm thinking it should actually be Resources? Let me check back).  

note from our team meeting: this might be the 5th button for at least first few years and then we might re-address it.

**Comment by barsenault-fsu** [comment]
Text for page

https://docs.google.com/document/d/1XeM75H453OW5VXp4M1NiIdd9DFRZVwEc_3RitJAk4YE/edit?usp=sharing

**Comment by barsenault-fsu** [comment]
The new button is on Test.  Ready for review

**Comment by barsenault-fsu** [comment]
New button is on production and linked to the provided page.  Closing.
