### ISSUE TITLE
Sample text: color shade

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#15]
Can you make the sample text (that exists in a field before they type something in) one shade darker? It's hard to see. It should NOT be the same dark gray that exists on the rest of the page. So if there is not a lighter gradient option, you can ignore this. Thanks!

**Comment by bryjbrown** [comment]
Placeholder text on test.ldbase.org is now one shade darker and easier to read. Please review and close this issue if you are satisfied with the solution, or respond here if you have further related issues.
