### ISSUE TITLE
Create a link

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#153]
On this screen:  Create/Edit Dataset
Where it says this text: "If you wish to contribute your data to LDbase's Integrated Dataset, check this box and you will be contacted by an administrator on how to proceed."
Can you make these words:  "LDbase's Integrated Dataset"
link to the "LDbase Integrated Dataset" that is located at: https://ldbase.org/projects/09609d82-c45f-4442-8c0c-d136191bdc50

**Comment by barsenault-fsu** [comment]
I added the link in the field description.

**Comment by barsenault-fsu** [comment]
This is on Production now, so I'm going to close the issue.
