### ISSUE TITLE
Project Description paragraph - using "Enter" key

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#154]
When typing the text, if you press the "Enter" key, it displays it to you as going to the next line (good). But then the display text that other people can see when viewing your project, does NOT show the divisions of new lines where you have hit the enter key. 
Please correct this here and anywhere else it would apply.

**Comment by barsenault-fsu** [comment]
The paragraph breaks should appear now in the display.

**Comment by barsenault-fsu** [comment]
This is fixed and on Production.
