### ISSUE TITLE
"Newsfeed" on LDbase

### ISSUE THREAD

**Issue by barsenault-fsu** [ldbase/ldbase_issues#156]
From Flock:  
'Sara was thinking we might need a "Newsfeed" on LDbase. Above the footer on homepage. Maybe some kind of a splash bar thing. We can announce things like "Join us the last Friday of the month at noon where we can answer any questions you have about LDbase!" and host a live Q&A type tech help thing.'

**Comment by barsenault-fsu** [comment]
Now on Test.  There is a newsfeed carousel on the front page above the gray "About LDbase" footer.  Each article has a title, article body, and optional image and tags.  The front page displays the title, the beginning of the body text truncated to 300 characters, and the image.  It links to a full display of the article.

The meeting notes for 9/28/2021 have a user guide for adding articles.

**Comment by barsenault-fsu** [comment]
This is now on Production.  The user guide for adding articles is linked from the 9/28 meeting notes.

I'll leave this open for now if you have any feedback.

**Comment by trreynolds** [comment]
1.) I added a news item, but the text is cut off (and it's not obvious that there is more text to see). Any ideas (like a grayed out "click for more details" or three dots or something)?
2.)  The "preview" button would not work when I was initially setting it up.
@barsenault-fsu

**Comment by barsenault-fsu** [comment]
1) Three dots added.  Title links to full text
2) Preview doesn't work with new articles because the preview relies on a node id to display some information.  Not a problem for other basic pages.  Workaround is to save as unpublished, edit, then preview.
(from [10-26-2021 meeting notes](https://docs.google.com/document/d/1wlPEUeggdTjBk-8bgCJ0sYjid0Nvc4xoVwqieuP6ibI/edit#heading=h.69khqdkimrzr))
