### ISSUE TITLE
Date displays

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#16]
For the “Project Active From” dates (and maybe other places where we display dates), can you display that as mm/dd/yyyy-mm/dd/yyyy? It currently looks like this:  1937-04-29 - 1936-05-01 (bjb: in addition to changing the display formatting, also if no end date, display something like “ongoing” or “to present”)

**Comment by barsenault-fsu** [comment]
The date is now formatted "Month Year to Month Year" and if there is no end date it reads "Month Year to present" instead.
