### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#163]
If you click on the homepage, inside of that first box you see (when logged in), it says "Edit Your Profle" LOL .. can you fix that and add the "i" in "Profile"?

**Comment by trreynolds** [comment]
While you're in there, I think on the "LDbase Terms of Use" page, the first instance of the word available should be removed, would you agree?  "Public API: An application program interface available is available to the public..."

**Comment by barsenault-fsu** [comment]
Both changed have been made and deployed to production.
