### ISSUE TITLE
Edit Dataset Webpage: word change

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#17]
On the Dataset Edit page, it says, "Dataset Investigators" and it should say "Dataset Contributors"

**Comment by barsenault-fsu** [comment]
Hmm I thought I had done that before in https://github.com/ldbase/ldbase_config/commit/5d8747e41452c1de5b0e6cada023ee185fc2c3ef?diff=split but I'll get it in the course of dataset version changes.

**Comment by barsenault-fsu** [comment]
I pushed https://github.com/ldbase/ldbase_config/commit/f78a5c425920cbd0d03d10c898ba1698057bbb2d that changes 'investigator' to 'contributor' in the label, description, help text, and add button.

**Comment by bryjbrown** [comment]
These changes are now present on test.ldbase.org, please review and close this issue if the problem has been resolved.
