### ISSUE TITLE
The clickable icons/page number listings at the bottom of lists users have to scroll through 

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#173]
Throughout LDbase, please add the correct format we decided on for 'lists' where a user has to click to get to the next page of a list of items they're reviewing. (the number of pages/previous/next thing, format and icons). We picked one during a meeting earlier this year. Should be applied throughout LDbase consistently and they should all look the same. 
One example where it didn't get updated is here (scrolling through this person's contributions, it erroneously shows "Page 1" and a next arrow): https://ldbase.org/persons/36c0d89e-6300-4dda-ba03-47f2b28040cf?page=0

**Comment by barsenault-fsu** [comment]
Changed to be consistent with other pagers.  For future reference, the Pager should be set to "Use Pager: Full | Paged Items: 10"

**Comment by trreynolds** [comment]
@barsenault-fsu this might be the code you were looking for in the team meeting last week.
