### ISSUE TITLE
Issues related to search

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#18]
LDbase now has an advanced search page that uses boolean operators, please review and log any feedback you have in this issue.

http://test.ldbase.org/advanced-search

**Comment by WilhelminavanDijk** [comment]
The advanced Boolean search works well! It's a little weird at first to not have to put in the boolean operator words yourself. We may need some extra language there at some point.


Here are some initial concerns:

1. The search only works for a complete name and not an approximation. For example, searching for Wilhel does not result in finding Wilhelmina. Should it do "fuzzy matching"? 

2. The search does not return queries for types of data (e.g., "raw scores"), participants (e.g., "Children"), or constructs (e.g., Attention). I didn't try out all the things, but it seems like it only finds words that are in titles?

3. After you click on a search result, it takes you to a new page with the overview. That's cool, but you then have to click the back button of your browser to get back to the search results page. Is there a way to either get a button to 'go back to results' or to go to a new tab when clicking on a search result item?

**Comment by WilhelminavanDijk** [comment]
Never mind previous #3, Sara does not like that idea.... oops.

Here's comment 4 from Sara:
Is there a way to make the results more organized? She'd like a short view to come up firs, with a button to extend to see full search results. (I think we have a screenshot from some other repo that we will share with you).

**Comment by bryjbrown** [comment]
1: Autocomplete and stemming (eg, a search for "contains" will match "containing", or "Mexican" will match "Mexico") have been added, but true "fuzzy search" ([n-gram](https://en.wikipedia.org/wiki/N-gram) search) is too much for our site to do as-is and would require setting up an external search server (Solr) to do. This would make LDbase more expensive to run and complicate the deployment process, but we are willing to do that if this is a hard requirement.

2: It should now. The labels for all controlled vocabulary terms are now indexed, so searching "microgenic" should now return datasets that have "Microgenic" selected for their "Time Method(s)".

3. I agree with Sara, the back button is adequate.

4. The search results have been rebuilt, and even the longest results don't take up TOO much space. Let me know if the new search results display doesn't satisfy this requirement, and if so, what else needs to be done.

**Comment by Favenzio** [comment]
Solution has been accepted.
