### ISSUE TITLE
All terms are not displayed when users are using Browse Features

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#180]
Browse is not displaying all terms that exist.  
An example, sent 12/2023:  this project says funding agency is IES (https://www.ldbase.org/projects/940d9455-b1a6-4985-8957-7c113b6530b6) so IES should come up as a Funding Agency when you "Browse our Data" and click on Funding Agency, right?

**Comment by barsenault-fsu** [comment]
same as #169
