### ISSUE TITLE
Ability for user to add a response that doesn't exist (dropdown lists, pill boxes, etc.)

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#21]
Where you can select from a pre-populated list: the user was supposed to be able to add a response (like, they can type in a new value) if their value isn't there.
We said we would monitor these additions on the back end for the first two years or so to decide if it's a valid response or not and whether it should be added permanently to our list. We think after a few years, we probably should have a pretty solid list and can decide at that point whether we will continue to allow people to add new values or not.

**Comment by barsenault-fsu** [comment]
I see 3 prepopulated lists with an "Other" option: Project Descriptors, Assessment Names, and Data Collection Locations.  I have added an "Other" text field which appears when the user selects the "Other" option in those lists.

Are there any other lists that require an "other" option?

**Comment by barsenault-fsu** [comment]
I have added the "Other" option to all of the pill box type select lists.

Still need a view or views of the terms that people add so that an administrator can review them to see if they should be added as selections.

**Comment by barsenault-fsu** [comment]
This is related to #36.  If the solution of automatically adding new term to taxonomies is acceptable, then these "Other" fields might be removed.

**Comment by barsenault-fsu** [comment]
Switching and customizing the Select2 library on the webform allows us to remove the "Other" fields. Any further developments can be tracked in issue #36 

Closing this issue.
