### ISSUE TITLE
Cite button

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#22]
"Cite This" button/hyperlink is needed on every project/dataset/document (or equivalent), right under title

**Comment by bryjbrown** [comment]
A "Get APA Citation" button has been added to all citable content types that renders an APA citation in a pop-up.

**Comment by WilhelminavanDijk** [comment]
Please change the name of the box from "get APA citation" to "get suggested citation".

(because it's not *exactly* APA, and people will be upset when they think it's correct and then need to change stuff)

**Comment by Favenzio** [comment]
Solution has been accepted.
