### ISSUE TITLE
Social Media Share

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#23]
share on social media buttons need to be available on every project/dataset/document, etc. 
When they click to share, can you autofill in “#LDbase”?  Please? :)

**Comment by bryjbrown** [comment]
Twitter + Facebook + Email for sharing platforms.

**Comment by bryjbrown** [comment]
Added social media block with integrations to Twitter, Facebook, Reddit and Email. Will discuss the default text for these integrations at 9/8 meeting.

**Comment by trreynolds** [comment]
Looked good! Feel free to close if you're done.

**Comment by Favenzio** [comment]
Solution has been accepted.
