### ISSUE TITLE
System Notifications

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#26]
Logged-in users can get system messages/notifications, like workshops or you haven’t finished uploading data.  (and we want the function to be able to send an email, like if someone requests their data)

**Comment by Favenzio** [comment]
Messaging feature has been implemented.

**Comment by trreynolds** [comment]
LDbase system admins need the ability to be able to send out a message to all registered LDbase users still. Our current situation is announcing workshops (LDbase Q&A sessions).

**Comment by barsenault-fsu** [comment]
Added a Mass Contact module for admins to send email to all LDbase users.  A user guide for the tool is attached to the 9/28/2020 meeting notes.

**Comment by barsenault-fsu** [comment]
The Mass Contact module is now on Production.  Remember the user guide is attached to the 9/28 meeting notes. 

I'm closing this issue.  If you encounter any issues, you can open another issue or let me know in Flock or Teams.
