### ISSUE TITLE
Lock symbol

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#27]
How will users know when a dataset is locked? 
-use a lock icon/symbol to make it clear in search results when data is open or not

**Comment by bryjbrown** [comment]
@trreynolds What do you mean by "when a dataset is locked"?

**Comment by trreynolds** [comment]
Locked = not able to be downloaded or viewed by public. AKA you have to ask permission of the owner.

**Comment by barsenault-fsu** [comment]
There are 3 indications that content is embargoed:
1. Notice at the top
![image](https://github.com/user-attachments/assets/dcc34005-b1a6-4c93-80da-7635b34875b7)
 
2. The link text changes and takes you to either the login screen or an access denied screen if you are already logged in
![image](https://github.com/user-attachments/assets/a839e02d-1869-419a-a21c-fc20a4185a0c)

3. The embargo details block appears on the page
![image](https://github.com/user-attachments/assets/c45978b7-7541-441d-a576-4f5ed0cbc58d)
