### ISSUE TITLE
Add People to your project

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#28]
We need a way to add users to a project, dataset, etc.

**Comment by barsenault-fsu** [comment]
Project Administrators can manage project users now.  Under the project tasks menu is a link to Manage Users.  From there the administrator can add users to the project, edit their roles (Administrator or Editor), and remove users from the project.

**Comment by barsenault-fsu** [comment]
People can be added to projects now by Project Administrators using the Manage Members link in the Project Tasks menu, which is visible when viewing a Project.  Those added people (users) become members of the project and can be given the Project Administrator role or the Project Editor role.  Both roles can edit content related to the project (datasets, code, etc.).  Project Administrators can add or remove people (users) from the project group.  When a user creates a project, they are automatically made the Project Administrator for the project.

**Comment by WilhelminavanDijk** [comment]
This worked! I added Brian as an admin to my projects 💯

**Comment by trreynolds** [comment]
Thanks, that works! As discussed earlier, the person added to a project should get a notification about being added.

**Comment by barsenault-fsu** [comment]
Users will now receive a notification message that they have been added to a project.
