### ISSUE TITLE
Remove entity IDs from values entered into entity reference autocomplete form elements

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#3]
Multiple forms have entity reference elements (autocomplete fields for entering persons, organizations, etc) and by default, Drupal displays the entity ID of values entered into these fields. For example, if referencing an entity named "Bryan Brown" with the entity ID 2, it will display this in the form as "Bryan Brown (2)". This is confusing for users, the entity ID should be hidden from users.

**Comment by barsenault-fsu** [comment]
Added JavaScript code to each webform to strip the entity ID from the display.
Config: https://github.com/ldbase/ldbase_config/commit/024a063c810611e8d8bfa64d2339e52f2b50b5ba

**Comment by WilhelminavanDijk** [comment]
Entity ID's are now stripped!

**Comment by barsenault-fsu** [comment]
Entity IDs are stripped so I'm closing this issue.  Looks like it was inadvertently linked to issue 18 by a github autocomplete (If you type an octothorpe then you can link to other issue numbers).
