### ISSUE TITLE
Change all instances of "username" to "email address"

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#30]
Users login with email, so label all fields accordingly

**Comment by barsenault-fsu** [comment]
I used ldbase_content_form_alter() to change the field title and descriptions on the user login form:
Username is now Email Address, and the field description (which only appears on user/login) reads, "Enter your LDbase account email address."
The password field description (which only appears on user/login) reads, "Enter the password that accompanies your LDbase account."

I'll label this issue "Needs Review" when it gets deployed to Test.

**Comment by barsenault-fsu** [comment]
On Test and ready for review.

**Comment by rkmase** [comment]
password reset page field needs to be changed to just "Email address"  http://test.ldbase.org/user/password

**Comment by barsenault-fsu** [comment]
Just pushed the password reset form change.  Once Test is updated it should just read, "Email Address"

**Comment by rkmase** [comment]
On profile edit - original email address needs to be locked, or a note needs to be added that says adding emails won't change their login
