### ISSUE TITLE
Validate email address when creating new account

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#32]
When creating new account, system should check whether email address exists

**Comment by Favenzio** [comment]
I assume you mean that it should do an ajax check as the email address is being input into the form? The form doesn't allow you to create a second account with the same email address, so it does check, it just does it after submit. If you just mean that it would be nice if the user was told as they were creating the account, then I agree, but I'll mark it as a nice to have, not a must have. Changing label to post-launch.

**Comment by barsenault-fsu** [comment]
This issue is resolved.  The validation is happening and issue #60 changes the redirect after the validation.
