### ISSUE TITLE
Autocomplete dropdowns should close after selecting an option

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#34]
When using an autocomplete field (example: Project Descriptors), after typing and selecting an option from the drop-down, the drop-down should disappear to allow access to next field, etc. Right now the user has to "click-away" in order to remove the drop-down. On mobile (in this example) the drop-down blocks the remaining fields and the Submit button.

**Comment by barsenault-fsu** [comment]
I pushed a change that should close those drop-downs each time an option is selected, which should appear on the test site once it is refreshed.

**Comment by barsenault-fsu** [comment]
Autocomplete dropdowns now close after selecting an option
