### ISSUE TITLE
When I click on a url link (in a project), please open site in another tab (so user does not exit ldbase).

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#35]
I was on my personal project page when this happened.

**Comment by bryjbrown** [comment]
This is a very controversial topic in user experience / usability / accessibility world, and the general consensus is that this SHOULD NOT happen for the following reasons:

1. Going to the new URL in the same tab is the default behavior of a web browser, and opening in a new tab is straying from that behavior. Websites should never do anything that surprises or confuses users' expectations.
2. Users can always see the URL and make the decision to open in a new tab on their own by right clicking and selecting "Open link in a new tab". We want to leave this decision to the user and not make it for them.
3. This breaks the ability of the browser's "Back" button. If they follow the link in the same tab they can always cycle back to the previous URL. When you open the link in a new tab, that new tab has no previous URL and the user could become confused.

For all these reasons, its a recommendation to NOT open any links in new tabs unless there is a specific reason why this MUST be done (See the Web Content Accessibility Guidelines write-up of it at https://www.w3.org/TR/WCAG20-TECHS/G200.html).

Mason (who doesn't appear to be on GitHub) is the UX expert in the group, so I'll run this by him as well to get his feelings on it.

**Comment by bryjbrown** [comment]
Whoops, it appears mason IS on GitHub @rkmase

**Comment by rkmase** [comment]
Yup, I agree with Bryan on this one. You let the user choose to open in a new tab, if they'd like (with the menu, or CTRL click), but you should never make that choice for them.

**Comment by trreynolds** [comment]
Great advice. Thank you! Issue closed.
