### ISSUE TITLE
Unable to add code to a project

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#38]
Schots: "Some code (like data management code or scoring code) could be particular to a dataset.  Other code (like analysis code) could be particular to a project or a paper."  (I'm pasting this comment here, simply so I can remember the LDbase requirements as I continue to test.)

**Comment by barsenault-fsu** [comment]
Users will be able to add code to a project.  This is not on test yet but should be ready to review at the 8/12 update meting.

**Comment by barsenault-fsu** [comment]
Users can add code to a project using the Add Code link in the Project Tasks menu, which is visible on the Project view.

**Comment by trreynolds** [comment]
That's perfect. Thanks. I think we still need to be able to better explain to the user what this code is that they are adding (aka, You are adding Code to the **Project Level** (code for entire project, or analyses code of whatever), not code that is specific to dataset management... as that code should be added in a different spot..) Would that perhaps be done via text on the screen or during the gamification process (Github issue #13?). If so, you can close this.

**Comment by barsenault-fsu** [comment]
Agreed, further explanation may be handled in #13.  Closing this issue.
