### ISSUE TITLE
Add Mplus files to allowed code

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#41]
Please ensure Mplus files can be added to code .inp and .out

**Comment by barsenault-fsu** [comment]
When the test server is updated, uploading Code files should now allow the following extensions:  rmd, do, inp, r, sas, txt, sps, py, m, out

Are there any other extensions that should be allowed?

**Comment by bryjbrown** [comment]
@barsenault-fsu For future reference, when we add any new allowed extensions, we also need to add them to the Matomo config so that they can be tracked. See https://github.com/ldbase/ldbase_config/commit/e0648dd0bd3848d02d5b9b2c2307b801225effd0

**Comment by WilhelminavanDijk** [comment]
Not that we can think of right now!

**Comment by barsenault-fsu** [comment]
Thank you.  Closing issue.
