### ISSUE TITLE
Automatic download

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#42]
When clicking on actually uploaded "data" (code, document, dataset), it will automatically download. Do we want this, or do we want there to be a download button/pop-up message?

I'm saying this because when clicking on other links on the pages, it takes you to displays of everything that has that particular content, and here it starts downloading. People might end up with data on their device that they not necessarily wanted?

**Comment by bryjbrown** [comment]
@WilhelminavanDijk I think making the link more clear that it will initiate a download would be good. Turning it into a button that says something like "Download abcd.pdf (PDF, 13KB)" is a common practice.

**Comment by Favenzio** [comment]
Changed download link into a button. Solution has been accepted.
