### ISSUE TITLE
Dates (revisited)

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#43]
When adding dates for a project, I can make the end date earlier than the start date. That should probs not happen?

**Comment by bryjbrown** [comment]
I think @barsenault-fsu at some point did some validation for that, but it might have been for a different form.

**Comment by barsenault-fsu** [comment]
@WilhelminavanDijk Do you remember what you entered?  It might help me figure out what's going on with the validation.

**Comment by WilhelminavanDijk** [comment]
Oh, I know what happened! I thought you would get an error when putting it in, but the message actually pops up when you try to submit.

My bad :) I'm impatient and just fixed it before submitting, haha. I will close this issue right away!
