### ISSUE TITLE
license type options

### ISSUE THREAD

**Issue by ashleyaedwards** [ldbase/ldbase_issues#45]
The only license type option for datasets should be Open Data Commons Attribution License (ODC-By). For all other documents the options should only be the creative commons license types, there are many others that we do not explain in the documentation, these should be removed.

**Comment by ashleyaedwards** [comment]
In our psych meeting today we decided we would like there to be an option for "None" , an option for "ODC-By" and an option for "Other" that has a required text field entry. And unlike the other fields, new entries should not be added to the list (i.e., people should only see the option of none, odc-by, and other.

**Comment by bryjbrown** [comment]
@ashleyaedwards That covers datasets and documents, what about code?

**Comment by ashleyaedwards** [comment]
@bryjbrown Can code also be covered by creative commons?

**Comment by bryjbrown** [comment]
@ashleyaedwards I'm sure it could be, the question is just whether thats the best fit for it. We can make the options for code whatever you all want, we just need to be told what it should be. Can you confirm with the rest of the psych team that you want Code to have the same CC license options that the documents have? And if not, what would you like instead?

**Comment by ashleyaedwards** [comment]
CC for code and documents are good. Same "other" option that allows people to type in their own but that does not get added to the list

**Comment by barsenault-fsu** [comment]
I'm almost done with this, but before sending it to Test I'd like to confirm the options for licenses.  Let me know if you want any changes. 

**Dataset**
- None
- Open Data Commons Attribution License (ODC-By)
- Other
  -  Enter Other ... (text field)

**Code and Document**
- None
- CC BY (Attribution)
- CC BY-NC (Attribution-Non-Commercial)
- CC BY-NC-ND (Attribution-NonCommercial-ShareAlike-NoDerivatives)
- CC BY-NC-SA (Attribution-NonCommercial-ShareAlike)
- CC BY-ND (Attribution-No-Derivatives)
- CC BY-SA (Attribution-Share-Alike)
- CC0 (No Rights Reserved)
- Other
  - Enter Other ... (text field)

**Comment by ashleyaedwards** [comment]
looks good
________________________________

**Comment by barsenault-fsu** [comment]
@Favenzio I used a different element to handle the license changes and now there is a border around the form field label on the forms for Dataset, Code, Document, and Codebook.  Can you please take a look at the CSS for this?

**Comment by WilhelminavanDijk** [comment]
The options seem to have been implemented correctly! Do we want a link to explanation of the license options for document? (this may be issue 49 instead and could be included in the hidden help text)

**Comment by Favenzio** [comment]
Solution has been accepted.
