### ISSUE TITLE
When Search Results return nothing

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#46]
Can there be some kind of a message like 'No results found' (or whatever is standard)?
If nothing is returned from a search, it just kind of repeats the search screen, and you're left feeling like you're not sure if the search worked or not.

**Comment by bryjbrown** [comment]
This is an easy fix, it'll be ready for the next meeting.

**Comment by bryjbrown** [comment]
Improvement is in place on test.ldbase.org, just search for a term that has no matches and see "No results found." in the results area.

**Comment by rkmase** [comment]
We should also consider alternate options when no results are present. (did you mean? subject suggestions based on search, etc) I'm not sure how feasible that is due to the backend and the subject matter, but its worth discussion post-launch. Users should always be given an option.

**Comment by barsenault-fsu** [comment]
links have been added to run canned searches for all Projects or Datasets and to try an advanced search
![image](https://github.com/user-attachments/assets/e2e32f07-905b-488c-8adf-3c15fcd930a8)
