### ISSUE TITLE
Search Results:  include project name

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#47]
I know you are working on a slimmed down version of returning information (per project) in the search results. Can you add "Project Title" to that?  
Reasoning: a lot of datasets might be named "final" or a poster might be named "Graduate Talk".  In search results, that might not make a whole lot of sense. But if it showed that it belonged to the "Core Knowledge in Language Arts" project, it might make it more helpful.

**Comment by bryjbrown** [comment]
@trreynolds Just to clarify, do you mean that a Dataset/Code/Document returned in a search should show the title of the parent project it belongs to? Something like:

**Project TEENS Reading Comprehension Dataset**
Project: Project Teens
Authors: Tara Reynolds
Description: A dataset full of reading comprehension test scores

**Comment by trreynolds** [comment]
Yes, exactly. Thanks! For a child, show the parent's projects title.

**Comment by barsenault-fsu** [comment]
Found a way to add the parent project as an indexed field on datasets, code, and documents.  Closing.
