### ISSUE TITLE
Add Field "Unique" to dataset

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#48]
A while ago we had discussed to have a field in the dataset form where users would indicate if the data set was unique, or a combination/slight deviation from already existing data.

We just noticed we don't have this yet, and this seems like a data-structure problem!

**Comment by bryjbrown** [comment]
@WilhelminavanDijk Can do, we just need a bit of input on the exact wording for the field label, info or help text and options, for instance:

Label: Unique or Derived?
Help: Is this dataset unique, or was it derived from another dataset?
Options: Unique, Derived

if "Derived":
Label: Derivation Source
Help: The source dataset(s) that this dataset was derived from
(repeatable URL fields)

**Comment by bryjbrown** [comment]
Assigning this to @barsenault-fsu because he'll be adding this to the form and webform handlers, but also tagging myself and @Favenzio because these data model changes will need to be reflected in the search and display too.

**Comment by WilhelminavanDijk** [comment]
> @WilhelminavanDijk Can do, we just need a bit of input on the exact wording for the field label, info or help text and options, for instance:
> 
> Label: Unique or Derived?
> Help: Is this dataset unique, or was it derived from another dataset?
> Options: Unique, Derived
> 
> if "Derived":
> Label: Derivation Source
> Help: The source dataset(s) that this dataset was derived from
> (repeatable URL fields)

I will add these field to the doc I'm creating for the changes to text in dataset form. (coming in an hour or so!)

**Comment by barsenault-fsu** [comment]
For reference, the dataset content type now has
1. field_data_unique_or_derived  [List(text)]
2. field_derivation_source [Link] (unlimited)

I committed the additional fields (They are not on test yet.  I'll try to remember to tag this issue as Needs Review when that happens.)

**Comment by WilhelminavanDijk** [comment]
This is working great! I think issue can be closed :)
