### ISSUE TITLE
Decide on terminology for "Home" and "My account"

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#5]
Currently, "Home" on LDbase refers to the front page, and "My account" refers to the user page, but some users may think of "My account" as their user's home, and get confused. To rectify this, we need to come up with specific terminology for the front page and the user page and use it consistently across the site.

**Comment by bryjbrown** [comment]
From Mason:
> I think what we're doing is good, as long as its consistent. I will say that a generic "Home" link typically signifies that link takes you to the main "home"page. What we need to decide what we're calling the account page - is it "Dashboard", "My account", "My stuff", "My projects", "[username]'s Home"? All of these are fine, but "[username]'s Home" typically signifies a customized home page (think Amazon) which I don't believe we are going to use.

**Comment by bryjbrown** [comment]
9/3 audit notes: "Home" is homepage, the front page of the site, and "My Dashboard" will be the user's home page where they can see their own content, profile, etc.

**Comment by trreynolds** [comment]
We love "Home" and "My Dashboard". Thanks!
