### ISSUE TITLE
Improve search facet interface

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#50]
From @WilhelminavanDijk in https://github.com/ldbase/ldbase_issues/issues/20:

"The filters on the search are not quite intuitive. Right now, each filter appears at the bottom of each category. It wasn't clear to me at first that that was what was happening. If you select multiple filters, for example, each filter stays under their own category.
Would it be possible for the filter to show up as pill boxes above the search? That way it would be clear how the search was filtered and easier to drop filters a user doesn't want. Alternatively, instead of clicking on the "links" on the left, we see checkboxes as an option to select filters."

Breaking out into a new issue here since this is a different issue.

**Comment by bryjbrown** [comment]
This is done and viewable on test.ldbase.org.

**Comment by Favenzio** [comment]
Solution has been accepted.
