### ISSUE TITLE
Example text (the grayed out words) for "Add Codebook" task 

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#51]
Ashley was asking if the "sample text" (that appears where people will type in their metadata) could display different language for the Codebook form. (It currently shows the normal "add document" language like, Document Title="SRCD Poster 2019".)  Is it possible to have different language for the "Add Codebook" task?
Reminder to myself for future conversation on this.. Ashley wants to push them to say what dataset the Codebook is connected to. For example, "Codebook for Wave 1 CKLA dataset" so that others see exactly what dataset the codebook goes with. -- a second thought, maybe we could add different text help for Codebook entries? Or maybe not because it uses just the general Document form text?)

**Comment by barsenault-fsu** [comment]
Yes, the Codebook form can have different placeholder text in the fields.  It's a separate form from the Document form, so that's an easy change once you give us the text you want to appear.

**Comment by WilhelminavanDijk** [comment]
We are working on this!

**Comment by trreynolds** [comment]
@WilhelminavanDijk, just to clarify, Ashley meant the grayed-out sample text that is in the background (what you will type on top of).. for the Codebook. She wants Codebook (rather than Document) language there and it could say this:

CODEBOOK NAME:  For example: Codebook for the Wave 2 Vocabulary Knowledge Grant dataset
CODEBOOK AUTHOR:  For example: Dr. Sally Shares
CODEBOOK DESCRIPTION:  For example: This doc holds the variable descriptions for the Wave 2 Vocabulary Knowledge Grant dataset. Our wave 2 dataset was slightly different than Wave 1, as we added some new fields. All variables, descriptions, and values for the Wave 2 dataset are explained in this document.

**Comment by WilhelminavanDijk** [comment]
Yes, all language for this is coming this wednesday after the psych meeting

**Comment by barsenault-fsu** [comment]
Since the text for this change came in the Change_Codebook document in issue #49 I'm going to close this.
