### ISSUE TITLE
Double boxes when reduce screen width

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#52]
Hi all,

I was using split screen with LDbase test site and noticed that it makes some of the field names appear double.
Attaching a screen shot here.
![Screen Shot 2020-09-23 at 8 20 15 PM](https://user-images.githubusercontent.com/64925394/94188467-6d81ae00-fe77-11ea-81ed-9ec65e6bbc74.png)

**Comment by Favenzio** [comment]
This must have been happening a few iterations ago. Checked it on Chrome and Firefox and I could not replicate the problem. Setting as ready for review.
