### ISSUE TITLE
Add options to Document Types

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#53]
For the Document Types field, we would like to add options:

Assessment materials
Application
Experiment files
Lab Procedures
Other

we do not need a open box for other

**Comment by barsenault-fsu** [comment]
I have added the new items to the taxonomy for Document Types.  Once this is moved to Test, then I will label this issue as Needs Review.

**Comment by WilhelminavanDijk** [comment]
Looking good!
