### ISSUE TITLE
Re-ordering fields on webforms

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#54]
We would like to re-order the fields on the various webforms.

See attached doc! (the columns show old order and new order, to be consistent across forms and be more thematically grouped).
[ReorderingForms.docx](https://github.com/ldbase/ldbase_issues/files/5409843/ReorderingForms.docx)

**Comment by barsenault-fsu** [comment]
I changed the field order on the forms.  When this gets pushed to Test I'll add the Needs Review label.

One question: on the Dataset form, there is a Variable Types field that used to be after the Special Populations field.  It's not listed on the changes document, so I moved it to keep it after the Special Populations field.  Is that where you want it?

**Comment by WilhelminavanDijk** [comment]
Let's put it after assessments, that would make more sense thematically!

**Comment by Favenzio** [comment]
solution has been accepted.
