### ISSUE TITLE
Required metadata

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#55]
We removed the "this field is required" flag a few months ago when some fields weren't working (just so we could get past it and enter data). Please make these fields "required" again:
PROJECT LEVEL:  Project Description (text field), Project Investigator(s), Project Descriptors (the pillboxes).
DATASET LEVEL: Description, Contributors
CODE LEVEL:  Title, Code Contributors, Code Type, Description
CODE BOOK:  Title, Codebook Authors, Description
DOCUMENT:  title, Document authors, description, document type

**Comment by barsenault-fsu** [comment]
These fields are set as required now.  Closing issue
