### ISSUE TITLE
Change "Code Type" from single selection to allow multiple selections

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#56]
Can we request that "Code Type" (Analyses, Data Management, etc) allow for people to select multiple options rather than one option?

**Comment by barsenault-fsu** [comment]
It can't be post launch.  Changing from a single select to a multi-select is a data structure change.

**Comment by barsenault-fsu** [comment]
Reviewed in the 11/10 meeting.  Got a thumbs-up.  Closing.
