### ISSUE TITLE
Uploading code or linking to an external link

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#57]
On the Code form...
I feel like we are asking an either/or:  are you uploading code, or do you  have a link to your code that is at an external location?
But I was able to do both (I uploaded code AND said an external location).  Is this ok?  If so, it needs to be clear that that's what happening (we can talk about this).
Also, if they are saying they are uploading code, and they don't upload code, maybe we could have a warning message of "hey! you forgot to upload your code!"
Example:  look at "Code for 2nd grade set that just removes identifiable information"  (you will see that I gave external link, but there is also code they can download).

**Comment by barsenault-fsu** [comment]
Reviewed in the 11/10 call.  If external is selected, then the URL is required.  If uploaded is selected, then the file is required.  Editing, selecting the opposite option, and saving will erase the previous file or url.  It sounded like this was acceptable, but I'll leave this open for now for any feedback during pre-testing data entry.

**Comment by trreynolds** [comment]
Is there a way to warn them, "you are deleting the file you previously uploaded" if they edit and switch (from previously uploaded file to providing a link), just so they know their file will be deleted from LDbase and they can't get it back?
I'm sure they would have a backup file and be able to upload it again if they need to, but I'm thinking since we are advertising that this is place where you can store your files, we should at least warn them before it gets deleted?
Thoughts?

**Comment by barsenault-fsu** [comment]
@trreynolds My thoughts regarding this: 
If there is a warning about the file, then there should probably be a warning that their external URL will get removed if they switch it to an upload; but we don't have a pop-up warning for users on every form when they switch an option, so I'm wondering if it would be a little overwrought to have one for this.  For this field we already have the text "Upload Code *or* Link ..." and the radio button choice changes the fields on the form.  I think it's pretty clear that it's a one-or-the-other situation.

I could add a help text (hover on question mark type text) that reads, "You may either upload your code or link to it.  LDbase will save the information selected here."  Or something else?

**Comment by barsenault-fsu** [comment]
Team discussed on 4/27 and decided the text and workflow are okay the way they are.  Closing.
