### ISSUE TITLE
Tab order is off for some form elements

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#6]
On some of the webforms, the tab order is incorrect and cycles inconsistently through the same element multiple times instead of moving on to the next element. This seems to happen consistently with entity reference elements which require tabbing through the help multiple times.

**Comment by bryjbrown** [comment]
I figured out what is causing this; any field where there can be multiple values (eg, "Project Investigators" in the Project form allows for one PI per textfield, but has the "Add Project Investigators" button to add more) also has a "container" element around all the potential textfields, and I guess the way they coded this container element messes with the way that browsers tab cycle through elements normally. Its cycling from the help text to the container element then to the actual text field, and if there are multiple textfields then it cycles from one textfield to the container element and then to the next textfield. 

Its unfortunate and not ideal, but not really something we can do much about and ultimately not that big a deal. I'd like to close the issue now that we know whats causing it, but I'll leave that up to the Psych team to determine whether we can let this one go or if it is a big enough problem to devote more resources towards fixing.

**Comment by barsenault-fsu** [comment]
I might have found what's causing the extra elements that are catching the tab navigation on multiple entry fields like the Project Investigator(s) .  It's the Help icon.  There's a label and help icon for each form element.  If the screen is wide enough, you can't see them, but if you narrow the screen they appear for each.

When I changed the text for many fields which removed the Help text (Issue 49), then the tab order worked fine, like for Project Organization(s).  So if you wanted to remove the Help text for the Authors fields on the forms and include the help in the description somehow, then I think this issue would disappear.  

![image](https://user-images.githubusercontent.com/54671134/94865074-f87c1e80-040a-11eb-8ef9-af3aad76f2cb.png)

**Comment by WilhelminavanDijk** [comment]
we definitely don't want to change the help text! @trreynolds how much of a problem do you think the tab order is?
I think most researchers don't use it much.

**Comment by barsenault-fsu** [comment]
I just tested the tab order on the web forms.  Tabbing moved on to the next element in order without getting stuck on any multiline fields as it was doing before.  Closing the issue
