### ISSUE TITLE
If user chooses a pre-existing email during account creation...

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#60]
it should put them back at the form with a notation/error message with the form still filled, NOT dump them at a login page with the error

**Comment by barsenault-fsu** [comment]
Made a change so if the user enters an already used email address, then they get returned to the form and the validation message is set on the email field like this
![image](https://user-images.githubusercontent.com/54671134/115282637-6c1c1980-a118-11eb-9d8c-851386b2530f.png)
