### ISSUE TITLE
Improve display of active search facets

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#62]
Currently an active search facet displays as a "pill" that can be closed at the top of the search, as requested in https://github.com/ldbase/ldbase_issues/issues/50. 

Additionally, we should have active facets float to the top of the facet list instead of the bottom, sometimes beyond the fold of the top 5 results requiring a user to click the "Show more" link. See the following images provided by Dr. Hart:
![clipboard-image](https://user-images.githubusercontent.com/3837461/101085317-446b5100-357d-11eb-95de-53d4b39d031f.png)
![clipboard-image (1)](https://user-images.githubusercontent.com/3837461/101085369-564cf400-357d-11eb-921e-e643a2c6d4d1.png)

**Comment by barsenault-fsu** [comment]
Looks like this also came up in usability testing as issue #109 and is addressed there

**Comment by barsenault-fsu** [comment]
Changes requested in issue 109 are done and moved to production.  Closing issue.
