### ISSUE TITLE
URL input needs validation or option to select protocol

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#67]

**Comment by barsenault-fsu** [comment]
I pushed config updates to the webforms that (1) change all the URL fields to text fields, (2) add a URL pattern requirement to them, and (3) add a jQuery onclick to the fields that pre-fills them with 'https://' if the field is empty.  (Not on test yet)

https://github.com/ldbase/ldbase_config/commit/d8136ee860654f24472f6f4c643012b5d6ca6436

**Comment by Favenzio** [comment]
@rkmase has accepted solution.
