### ISSUE TITLE
Data Seal of Approval

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#68]
Can you apply for the Data Seal of Approval?  Let me know if I can help with this.  Thanks!

**Comment by bryjbrown** [comment]
[Data Seal of Approval](https://www.coretrustseal.org/about/history/data-seal-of-approval-synopsis-2008-2018/) doesn't exist anymore, it has been replaced by [CoreTrustSeal](https://www.coretrustseal.org/). Application costs €1,000 (~$1,200), and is centered on 16 requirements outlined at https://zenodo.org/record/3638211#.YBG1ked7mUk.

**Comment by trreynolds** [comment]
We would like to get this (post launch if needed). Are all technical requirements in place to do this?

**Comment by bryjbrown** [comment]
Listing this for posterity: 
https://docs.google.com/document/d/1kWVUhAMCuy8sbRqgMkXx0YZHcXvzMK4Fnxk1r-o5Ttg/edit

**Comment by barsenault-fsu** [comment]
There was a workshop at the Open Repositories conference this year called "How repositories can increase their FAIR share" and the first half or so talks about the process of applying for CoreTrustSeal certification.  The recording is at https://zenodo.org/record/4907579#.YMdj8PlKj-i
