### ISSUE TITLE
Lock context in place for long pages & forms

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#7]
Sometimes when scrolling through a long page or form, a user might forget what they are editing and/or what project they are working in. Having some sort of reminder at the top of the page to give them their context that locks in place when scrolling would be helpful.

**Comment by trreynolds** [comment]
I'm responding to the tag "Need clarification from Psy Team": 
This is when entering data into LDbase. Surprisingly, it's easy to forget what you are doing (what colleagues am I entering now? What age range am I entering now? What geographical location am I entering again?).  Locking something on the top of the screen showing the dataset/project/codebook  (or having a visual on the left like we talked about to show you where you are in the process of entering your project) would work. Low priority.

**Comment by bryjbrown** [comment]
I believe that the answer to this that we settled on was having the breadcrumbs, which show the current object and the path to it (its context within a project) locked to the top of the screen so that they are always there. For a time we had the Project Navigation Tree View block on the side of forms, but it was decided by the dev team that this took up too much space on an already cramped form so we removed them. 

Please respond indicating that the locked breadcrumbs are adequate to resolve this, or if more is needed.

**Comment by Favenzio** [comment]
Solution has been accepted.
