### ISSUE TITLE
"Unique" data label & location

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#74]
Issue: If you're downloading data, is it obvious that this is NOT unique data? 
After doing a query, when you click on a dataset, we would like to move the “Unique or Not” item up closer to the top of the info screen. We will change the descriptor text for this to better explain at a glance what this means.  
(History: We discussed if this should be a facet delimiting selection, but Shots said when doing metadata, it’s hard to define what is “unique or not”, as it is typically something the meta-analyses has to wrestle with. Schots decided: No, doesn’t need to be in facets.)

**Comment by Favenzio** [comment]
Unique or derived field has been moved up in the dataset display.

**Comment by trreynolds** [comment]
Location you moved it to is perfect. Sara wants to add one of those "?" bubbles (for help text) to a field on the "Viewing a Dataset" screen (see attachment)..  for the "Unique" field, to quickly explain to the public what this label means. The help text should say:
If data were collected specifically for this project and are not stored in a slightly different form elsewhere, they are unique. If these data combine or use data from other datasets, they are derived.
This was discussed with Brian/Bryan on Flock and they thought it would be possible. 
![unique](https://user-images.githubusercontent.com/64669172/107719221-b5c62f00-6ca5-11eb-9e1f-1d3146d00a48.JPG)
This was discussed on flock with Brian and Bryan. \

**Comment by barsenault-fsu** [comment]
There is now a help tooltip on the dataset view for this field using the text supplied above.  I tried to make it look just like the form help.  Let us know if this works.

**Comment by barsenault-fsu** [comment]
Solution accepted.  Closing.
