### ISSUE TITLE
Two typos

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#75]
Please remove the colon and space in our footer on "Grant #: R01HD095193"  should just be "Grant #R01HD095193".
On the About-LDbase team page, please spell Schots's name: Christopher Schatschneider

**Comment by Favenzio** [comment]
Removed colon from site footer. Could not find misspelling of Schot's name in the About LDbase page. Will review next meeting.

**Comment by trreynolds** [comment]
It's on this page:  http://test.ldbase.org/about/ldbase-team

**Comment by Favenzio** [comment]
Thanks for the clarification @trreynolds. I was able to find it. Will push to test at noon.

**Comment by Favenzio** [comment]
@trreynolds has accepted solution.
