### ISSUE TITLE
Find more flexible solution for providing dates

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#8]
Currently any project that makes use of date form elements, usually in the form of date ranges, has to enter year+month+day, but users might want to enter only year+month or even year only, because they might not always know the day or month that something began on. The form elements should be flexible to account for this.

**Comment by bryjbrown** [comment]
The default and current way we are handling this is to make the field store a Year + Month + Day (complete date), but we have found an alternative that would allow us to do a Year or Year + Month (but NOT a Year + Month + Date).

An additional option would be to store the entire date range as a plain text field so that people could enter whatever they wanted in whatever format they wanted, and just display whatever they entered. The downside to this is that we would then not be able to parse the dates to use them in views or as search facets (eg, show me all datasets produced from January 2017 - June 2019).

So the development team needs the psych team to decide whether Year or Year + Month (but no Day) is acceptable, or if you would prefer the flexibility of doing it as free text and lose the power to use the dates as search facets. Additionally, if neither of these options are acceptable we can continue to look for more options.

**Comment by barsenault-fsu** [comment]
After talking about it, we will change the date fields to composite fields with a month select and a year select, storing numeric data for each.  I'll provide a list here of the affected fields, and the teams can decide if any of them should not be changed.

**Comment by barsenault-fsu** [comment]
The date fields in the system are below.  I'm guessing the "Access Restriction Expiration Date" should remain as dates to support the embargoes, but that the others can become month/date. 

**Project**
-- Project Dates (Date Range)

**Datasets**
-- When was the data in this dataset collected? (Date Range)
-- _Access Restriction Expiration Date_ (Date - Keep?) 
-- Publication Date (Date) 

**Code**
-- _Access Restriction Expiration Date_ (Date - Keep?) 
-- Publication Date (Date) 

**Document/Codebook**
-- _Access Restriction Expiration Date_ (Date - Keep?) 
-- Publication Date (Date)

**Comment by barsenault-fsu** [comment]
Update: Forms have been modified so that date fields, except for the Embargoes' Access restriction Expiration date, are now Month / Year drop-down selections.  The display of the dates still need formatting but the form and data changes are made and could be reviewed.

**Comment by WilhelminavanDijk** [comment]
Ok. Those are working, however, on the overview pages, the months are converted into numbers. Can that be changed to names?

**Comment by barsenault-fsu** [comment]
The months appear as month names rather than numbers now.  We looked at these in one of the update meetings so I'm going to close this issue.
