### ISSUE TITLE
Sara's mockups

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#83]
Sara created a document in our Interface Mockups folder titled "Virtual Notes....". Leaving the reminder here to re-address this when you are ready.

**Comment by trreynolds** [comment]
Just noting that we had talked about eventually having usage data (altmetrics? others?)  at a higher level, not just per page, to be shared. We talked about having this on the front page or the “2nd home page”. Noting it here so it doesn't get forgotten.

**Comment by trreynolds** [comment]
> Just noting that we had talked about eventually having usage data (altmetrics? others?) at a higher level, not just per page, to be shared. We talked about having this on the front page or the “2nd home page”. Noting it here so it doesn't get forgotten.

I moved this to it's own, new github

**Comment by trreynolds** [comment]
When do we refresh the look of LDbase?

**Comment by barsenault-fsu** [comment]
Issue has been moved to another issue (#175)
