### ISSUE TITLE
Google Chrome saying "not secure" website

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#84]
My google chrome says the test site is not secure. I think this is just because it's our test site. Will this message be there when we go live with the real site?

**Comment by Favenzio** [comment]
Yes, you are correct. The test site is insecure because we have not acquired an SSL certificate yet. We will make sure the production server is secure prior to launch. Thank you for pointing out this issue.

**Comment by trreynolds** [comment]
Thanks, @Favenzio!

**Comment by Favenzio** [comment]
SSL Certificate has been issued and installed. Closing this ticket.
