### ISSUE TITLE
FCRR Admin Account

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#85]
Just making sure we have a way for one of us (FCRR) to be able to add/edit all metadata and data on the site (even if we are not a Project Admin or Project Editor). This will be helpful during the beginning when we are helping researchers set up their projects.

**Comment by barsenault-fsu** [comment]
I created a new FCRR Admin role, giving it a subset of administrator permissions to add/edit/delete content, add/edit/delete taxonomy terms, bypass groups permissions, and administer messages.  Also added the FCRR Admin role where admins are emailed by LDbase, such as when a new taxonomy term is added and when the report a problem form is complete.

When this is moved to Test, I will tag as need review.

**Comment by barsenault-fsu** [comment]
I added the FCRR Admin role on the production site to Tara and Sara
