### ISSUE TITLE
Finalize CrossRef DOI minting

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#87]
Currently test.ldbase.org creates generates DOIs and inserts them into the node metadata, but the generated DOI is not minted with CrossRef. This last bit needs to be implemented before receiving production data in order to ensure that DOIs given to production data work correctly.

**Comment by Favenzio** [comment]
Willa created a project in LDbase prod and a DOI was created successfully.  https://doi.org/10.33009/ldbase.1616514950.a4f3 Assume this issue can be closed.
