### ISSUE TITLE
Sometimes form location subelements do not display prepopulated lists

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#9]
Tara reports that sometimes she does not see the prepopulated lists for form location subelements, for example state and city.

Bryan cannot reproduce this issue.

Tara, can you provide more information? For instance:
- What browsers have you tried? (please try in others to see if the issue persists)
- What operating system are you using?
- Does this happen with other countries? (please try other countries)

**Comment by trreynolds** [comment]
Cities were no longer getting populated after selecting State. In Ldbase biweekly, Psy team leaders said it's ok for users to just type in the values for City.
