### ISSUE TITLE
A way for public to flag us to let us know they want to contribute to Harmonized Table

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#95]
Add a flag during data entry asking them if they want to add this data to our harmonized dataset (?). We will get an email and deal with it from there for now.  Sara will be providing you with the text for this.

**Comment by barsenault-fsu** [comment]
@trreynolds I'm going to add the "harmonized dataset" field to the Dataset data structure, form, and put together an email that will go to site administrators.  Please let me know when you have text for the field and email, and where on the dataset form you would like the field to appear.

**Comment by barsenault-fsu** [comment]
The field is on Test now and is part of the data model.  I need clarification on the language and where on the form you would like the field.  Currently it's between "Are these data unique?" and License.

**Comment by trreynolds** [comment]
The language:  
Would you like to add this data to LDbase's Integrated Dataset?
If you wish to contribute your data to LDbase's Integrated Dataset, check this box and you will be contacted by an administrator on how to proceed.

**Comment by barsenault-fsu** [comment]
Text changed.  Will update to Needs Review when moved to Test

**Comment by trreynolds** [comment]
Thanks, @barsenault-fsu !
